name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with pytest
        run: |
          export PYTHONPATH=src
          pytest tests/ --disable-warnings -v

      - name: Build app (if applicable)
        run: |
          echo "Add your build steps here, e.g., pyinstaller or Docker build"

      - name: Deploy app (optional)
        if: github.ref == 'refs/heads/main' && success()
        run: |
          echo "Add deployment script here, e.g., SSH deploy or cloud CLI commands"
